version: '2'
services:
 nginx:
  build:
   context: .
  environment:
      - VIRTUAL_HOST=${domain}
  volumes:
    - ./logs:/var/log/nginx/log
    - ./web:/usr/share/nginx/html
  ports:
    - "80:80"
